name: 'Hello World'
description: 'Greet someone'

inputs:
  passparamone:  
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - run: ls
      shell: bash
    
    - run: npm ci
      shell: bash   

    - run: ls
      shell: bash
    
    - run: chmod +x goodbye.sh
      shell: bash

    - run: ./goodbye.sh ${{ inputs.passparamone }}
      shell: bash