name: 'Hello World'
description: 'Greet someone'

inputs:
  passparamone:  
    description: 'Who to greet'
    required: true
    default: 'World'
  
  inputDir:  
    description: 'Inpout directoryt'
    required: true
    default: 'input'

runs:
  using: "composite"
  steps:
    - name: run install
      shell: bash
      run: |
        npm install --global imagemin-cli imagemin-gifsicle imagemin-mozjpeg imagemin-pngquant

    - name: run compression
      shell: bash
      run: |
        imagemin ${{ inputs.inputDir }} --out-dir=dist --plugin.mozjpeg.quality=40 --plugin.gifsicle.optimizationLevel=3 --plugin.pngquant.quality=0.4 --plugin.pngquant.quality=0.6
