name: 'Hello World'
description: 'Greet someone'

inputs:  
  inputDirectory:  
    description: 'Inpout directoryt'
    required: true
    default: 'input'
  
  outputDirectory:  
    description: 'Output directoryt'
    required: true
    default: 'dist'

  jpgCompressionQuality:  
    description: 'jpgcpom'
    required: true
    default: 40

runs:
  using: "composite"
  steps:
    - name: run install
      shell: bash
      run: |
        npm install imagemin-cli imagemin-gifsicle imagemin-mozjpeg imagemin-pngquant --global --loglevel error
    
    - name: run help
      shell: bash
      run: |
        imagemin --help

    - name: run compression
      shell: bash
      run: |
        imagemin ${{ inputs.inputDirectory }} \
          --out-dir=${{ inputs.outputDirectory }} \
          --plugin.mozjpeg.quality=${{ inputs.jpgCompressionQuality }} \
          --plugin.gifsicle.optimizationLevel=3 \
          --plugin.pngquant.quality=0.4 \
          --plugin.pngquant.quality=0.6

    - name: fefe
      shell: bash
      run: |
        echo "$(du -hs ${{ inputs.outputDirectory }} --apparent-size | cut -d$'\t' -f 1)"

    - name: Group of log lines
      shell: bash
      run: |
          echo "::group::My title"
          echo "$(du -hs ${{ inputs.outputDirectory }} --apparent-size | cut -d$'\t' -f 1)"
          echo "::endgroup::"
