name: 'Hello World'
description: 'Greet someone'

inputs:
  passparamone:  
    description: 'Who to greet'
    required: true
    default: 'World'
  
  inputDir:  
    description: 'Inpout directoryt'
    required: true
    default: 'input'

runs:
  using: "composite"
  steps:
    - name: Create package json
      shell: bash
      run: |
        cat <<EOF > $HOME/package.json
        {
          "name": "compressimages",
          "version": "0.0.1",
          "author": "Clyde D'Souza",
          "scripts": {
            "help": "imagemin",
            "go": "imagemin public/* --out-dir=dist --plugin.mozjpeg.quality=40 --plugin.gifsicle.optimizationLevel=3 --plugin.pngquant.quality=0.4 --plugin.pngquant.quality=0.6"
          },
          "devDependencies": {
            "imagemin-cli": "^7.0.0",
            "imagemin-gifsicle": "^7.0.0",
            "imagemin-mozjpeg": "^10.0.0",
            "imagemin-pngquant": "^9.0.2"
          }
        }
        EOF

    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash

    # - run: ls
    #   shell: bash
    
    # - run: dir
    #   shell: bash
    
    - run: npm install
      shell: bash
    
    - name: run shell script
      shell: bash
      run: |
        echo "First arg: ${{ inputs.passparamone }}"
        npm run go -- ${{ inputs.inputDir }} --out-dir=dist --plugin.mozjpeg.quality=40 --plugin.gifsicle.optimizationLevel=3 --plugin.pngquant.quality=0.4 --plugin.pngquant.quality=0.6
    
    # - run: sudo chmod +x ./goodbye.sh
    #   shell: bash

    # - run: ./goodbye.sh ${{ inputs.passparamone }}
    #   shell: bash