name: 'Hello World'
description: 'Greet someone'

inputs:  
  inputDirectory:  
    description: 'Inpout directoryt'
    required: true
    default: 'input'
  
  outputDirectory:  
    description: 'Output directoryt'
    required: true
    default: 'dist'

  jpgCompressionQuality:  
    description: 'jpgcpom'
    required: true
    default: 40

runs:
  using: "composite"
  steps:
    - name: run install
      shell: bash
      run: |
        npm install --global imagemin-cli imagemin-gifsicle imagemin-mozjpeg imagemin-pngquant

    - name: run compression
      shell: bash
      run: |
        imagemin ${{ inputs.inputDirectory }} \
          --out-dir=${{ inputs.outputDirectory }} \ 
          --plugin.mozjpeg.quality=${{ inputs.jpgCompressionQuality }} \ 
          --plugin.gifsicle.optimizationLevel=3 \ 
          --plugin.pngquant.quality=0.4 \
          --plugin.pngquant.quality=0.6

    - name: fefe
      shell: bash
      run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
