on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3

      - uses: .github/actions/compressimages
        with:
          passparamone: 'Mona the Octocat'
      
      - run: echo "$PATH"    